# Development Environment Configuration
# This file contains development-specific overrides

development:
  server:
    port: 8080
    host: "0.0.0.0"
    read_timeout: 30
    write_timeout: 30
    graceful_shutdown_timeout: 30
  
  database:
    host: "localhost"
    port: 5433
    user: "postgres"
    password: "password"
    name: "loan_service"
    ssl_mode: "disable"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300
  
  conductor:
    base_url: "http://localhost:8082"
    timeout: 30
    retry_attempts: 3
    retry_delay: 1000
  
  logging:
    level: "debug"
    format: "console"
    output: "stdout"
    enable_console: true
    enable_file: false
    file_path: "./logs/loan-service.log"
    max_size: 100
    max_age: 30
    max_backups: 10
  
  security:
    jwt_secret: "dev-secret-key-change-in-production"
    jwt_expiration: 3600
    bcrypt_cost: 12
    cors_allowed_origins: ["*"]
    cors_allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    cors_allowed_headers: ["Content-Type", "Authorization", "X-Request-ID", "X-Language"]
  
  application:
    name: "loan-service"
    version: "v1.0.0"
    environment: "development"
    max_loan_amount: 50000
    min_loan_amount: 5000
    max_dti_ratio: 0.43
    default_interest_rate: 8.5
    max_interest_rate: 15.0
    min_interest_rate: 5.0
    offer_expiration_hours: 168  # 7 days
  
  i18n:
    default_language: "en"
    supported_languages: ["en", "vi"]
    fallback_language: "en"
