# Base configuration with common settings across all environments
# This file contains shared configuration that doesn't change between environments

service:
  name: "underwriting-worker"
  version: "1.0.0"

server:
  read_timeout: 30
  write_timeout: 30
  graceful_shutdown_timeout: 30
  idle_timeout: 60
  cors:
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization", "X-Request-ID", "X-Language"]
    credentials: true

database:
  ssl_mode: "disable"
  conn_max_lifetime: 300

conductor:
  timeout: 30
  retry_attempts: 3
  retry_delay: 1000
  update_retry_time_ms: 3000

services:
  credit_bureau:
    provider: "experian"
    base_url: "https://api.experian.com"
    timeout_seconds: 30

  risk_scoring:
    provider: "internal"
    model_version: "v2.1"
    timeout_seconds: 15

  income_verification:
    provider: "plaid"
    base_url: "https://api.plaid.com"
    timeout_seconds: 20

  decision_engine:
    provider: "internal"
    timeout_seconds: 10

  notification:
    provider: "sendgrid"
    base_url: "https://api.sendgrid.com"
    timeout_seconds: 10

logging:
  format: "json"
  max_size: 100
  max_age: 30
  max_backups: 10

security:
  jwt_expiration: 3600
  cors_allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_allowed_headers: ["Content-Type", "Authorization", "X-Request-ID", "X-Language"]

application:
  name: "underwriting-worker"
  version: "1.0.0"
  min_loan_amount: 5000
  max_dti_ratio: 0.43
  default_interest_rate: 8.5
  max_interest_rate: 15.0
  min_interest_rate: 5.0
  offer_expiration_hours: 168

i18n:
  default_language: "en"
  supported_languages: ["en", "vi"]
  fallback_language: "en"

monitoring:
  metrics_enabled: true
  health_check_enabled: true
