#!/bin/bash

# Document Management API Examples
# Make sure the loan service is running on localhost:8080

BASE_URL="http://localhost:8080/api/v1"

echo "=== Document Management API Examples ==="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}1. Upload Document for Loan Application${NC}"
echo "POST /loans/documents/upload"
echo ""
echo "Example 1: Upload ID Document"
echo "curl -X POST \"${BASE_URL}/loans/documents/upload\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: en\" \\"
echo "  -d '{"
echo "    \"applicationId\": \"app-123-456-789\","
echo "    \"userId\": \"user-abc-def-123\","
echo "    \"documentType\": \"government_id\","
echo "    \"fileName\": \"drivers_license.pdf\","
echo "    \"fileSize\": 2048576,"
echo "    \"contentType\": \"application/pdf\","
echo "    \"metadata\": {"
echo "      \"documentSubType\": \"drivers_license\","
echo "      \"expirationDate\": \"2028-12-31\","
echo "      \"issuingState\": \"CA\","
echo "      \"pageCount\": 2"
echo "    }"
echo "  }'"
echo ""

echo "Example 2: Upload Income Statement"
echo "curl -X POST \"${BASE_URL}/loans/documents/upload\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: en\" \\"
echo "  -d '{"
echo "    \"applicationId\": \"app-123-456-789\","
echo "    \"userId\": \"user-abc-def-123\","
echo "    \"documentType\": \"income_verification\","
echo "    \"fileName\": \"paystub_latest.pdf\","
echo "    \"fileSize\": 1024000,"
echo "    \"contentType\": \"application/pdf\","
echo "    \"metadata\": {"
echo "      \"documentSubType\": \"paystub\","
echo "      \"payPeriod\": \"2025-07-01_to_2025-07-15\","
echo "      \"employer\": \"ABC Company Inc\","
echo "      \"grossPay\": 5000.00"
echo "    }"
echo "  }'"
echo ""

echo "Example 3: Upload Bank Statement"
echo "curl -X POST \"${BASE_URL}/loans/documents/upload\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: vi\" \\"
echo "  -d '{"
echo "    \"applicationId\": \"app-123-456-789\","
echo "    \"userId\": \"user-abc-def-123\","
echo "    \"documentType\": \"bank_statement\","
echo "    \"fileName\": \"bank_statement_july_2025.pdf\","
echo "    \"fileSize\": 3145728,"
echo "    \"contentType\": \"application/pdf\","
echo "    \"metadata\": {"
echo "      \"statementPeriod\": \"2025-07\","
echo "      \"bankName\": \"Chase Bank\","
echo "      \"accountType\": \"checking\","
echo "      \"accountNumber\": \"****1234\""
echo "    }"
echo "  }'"
echo ""

echo -e "${YELLOW}Expected Response (Success):${NC}"
echo "{"
echo "  \"success\": true,"
echo "  \"documentId\": \"doc-789-abc-def\","
echo "  \"uploadedAt\": \"2025-08-15T10:30:00Z\","
echo "  \"validationStatus\": \"pending\","
echo "  \"metadata\": {"
echo "    \"processingId\": \"proc-123-456\","
echo "    \"estimatedProcessingTime\": \"5-10 minutes\""
echo "  }"
echo "}"
echo ""

echo "================================================="
echo ""

echo -e "${BLUE}2. Get Document Collection Status${NC}"
echo "GET /loans/applications/{id}/documents/status"
echo ""
echo "Example 1: Check status for application"
echo "curl -X GET \"${BASE_URL}/loans/applications/app-123-456-789/documents/status?userId=user-abc-def-123\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: en\""
echo ""

echo "Example 2: Check status with different user"
echo "curl -X GET \"${BASE_URL}/loans/applications/app-987-654-321/documents/status?userId=user-xyz-789-456\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: vi\""
echo ""

echo -e "${YELLOW}Expected Response (Success):${NC}"
echo "{"
echo "  \"applicationId\": \"app-123-456-789\","
echo "  \"userId\": \"user-abc-def-123\","
echo "  \"status\": \"in_progress\","
echo "  \"totalRequired\": 4,"
echo "  \"collected\": 3,"
echo "  \"pending\": 1,"
echo "  \"documents\": {"
echo "    \"government_id\": {"
echo "      \"documentType\": \"government_id\","
echo "      \"collected\": true,"
echo "      \"validated\": true,"
echo "      \"fileName\": \"drivers_license.pdf\","
echo "      \"fileSize\": 2048576,"
echo "      \"uploadedAt\": \"2025-08-15T10:30:00Z\","
echo "      \"validatedAt\": \"2025-08-15T10:35:00Z\","
echo "      \"errors\": []"
echo "    },"
echo "    \"income_verification\": {"
echo "      \"documentType\": \"income_verification\","
echo "      \"collected\": true,"
echo "      \"validated\": true,"
echo "      \"fileName\": \"paystub_latest.pdf\","
echo "      \"fileSize\": 1024000,"
echo "      \"uploadedAt\": \"2025-08-15T10:32:00Z\","
echo "      \"validatedAt\": \"2025-08-15T10:37:00Z\","
echo "      \"errors\": []"
echo "    },"
echo "    \"bank_statement\": {"
echo "      \"documentType\": \"bank_statement\","
echo "      \"collected\": true,"
echo "      \"validated\": false,"
echo "      \"fileName\": \"bank_statement_july_2025.pdf\","
echo "      \"fileSize\": 3145728,"
echo "      \"uploadedAt\": \"2025-08-15T10:33:00Z\","
echo "      \"errors\": [\"Document quality needs improvement\"]"
echo "    },"
echo "    \"employment_verification\": {"
echo "      \"documentType\": \"employment_verification\","
echo "      \"collected\": false,"
echo "      \"validated\": false,"
echo "      \"errors\": []"
echo "    }"
echo "  },"
echo "  \"collectionStarted\": \"2025-08-15T10:30:00Z\","
echo "  \"validationErrors\": {"
echo "    \"bank_statement\": [\"Document quality needs improvement\", \"Please upload a clearer image\"]"
echo "  }"
echo "}"
echo ""

echo "================================================="
echo ""

echo -e "${BLUE}3. Complete Document Collection${NC}"
echo "POST /loans/applications/{id}/documents/complete"
echo ""
echo "Example 1: Complete collection (all documents ready)"
echo "curl -X POST \"${BASE_URL}/loans/applications/app-123-456-789/documents/complete\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: en\" \\"
echo "  -d '{"
echo "    \"userId\": \"user-abc-def-123\","
echo "    \"force\": false"
echo "  }'"
echo ""

echo "Example 2: Force complete collection (bypass validation errors)"
echo "curl -X POST \"${BASE_URL}/loans/applications/app-123-456-789/documents/complete\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: en\" \\"
echo "  -d '{"
echo "    \"userId\": \"user-abc-def-123\","
echo "    \"force\": true"
echo "  }'"
echo ""

echo "Example 3: Complete with Vietnamese language preference"
echo "curl -X POST \"${BASE_URL}/loans/applications/app-987-654-321/documents/complete\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -H \"X-Language: vi\" \\"
echo "  -d '{"
echo "    \"userId\": \"user-xyz-789-456\","
echo "    \"force\": false"
echo "  }'"
echo ""

echo -e "${YELLOW}Expected Response (Success):${NC}"
echo "{"
echo "  \"success\": true,"
echo "  \"message\": \"Document collection completed successfully\""
echo "}"
echo ""

echo -e "${RED}Expected Response (Error - Missing Documents):${NC}"
echo "{"
echo "  \"error\": \"Document collection incomplete\","
echo "  \"code\": \"LOAN_030\","
echo "  \"details\": \"Missing required documents: employment_verification\""
echo "}"
echo ""

echo "================================================="
echo ""

echo -e "${GREEN}Complete Test Workflow Example:${NC}"
echo ""
echo "# 1. First, create a loan application to get an application ID"
echo "curl -X POST \"${BASE_URL}/loans/applications\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Authorization: Bearer your-jwt-token-here\" \\"
echo "  -d '{"
echo "    \"user\": {"
echo "      \"first_name\": \"John\","
echo "      \"last_name\": \"Doe\","
echo "      \"email\": \"john.doe@example.com\","
echo "      \"phone_number\": \"+1234567890\","
echo "      \"date_of_birth\": \"1990-01-01\","
echo "      \"ssn\": \"123456789\","
echo "      \"address\": {"
echo "        \"street_address\": \"123 Main St\","
echo "        \"city\": \"New York\","
echo "        \"state\": \"NY\","
echo "        \"zip_code\": \"10001\","
echo "        \"country\": \"USA\","
echo "        \"residence_type\": \"own\","
echo "        \"time_at_address_months\": 24"
echo "      },"
echo "      \"employment_info\": {"
echo "        \"employer_name\": \"ABC Company\","
echo "        \"job_title\": \"Software Engineer\","
echo "        \"work_phone\": \"+1234567890\","
echo "        \"time_employed_months\": 36"
echo "      },"
echo "      \"banking_info\": {"
echo "        \"bank_name\": \"Chase Bank\","
echo "        \"account_type\": \"checking\","
echo "        \"account_number\": \"1234567890\","
echo "        \"routing_number\": \"021000021\""
echo "      }"
echo "    },"
echo "    \"loan_amount\": 25000,"
echo "    \"loan_purpose\": \"debt_consolidation\","
echo "    \"requested_term_months\": 60,"
echo "    \"annual_income\": 75000,"
echo "    \"monthly_income\": 6250,"
echo "    \"monthly_debt_payments\": 1500,"
echo "    \"employment_status\": \"full_time\""
echo "  }'"
echo ""
echo "# 2. Upload required documents (use application ID from step 1)"
echo "# 3. Check document collection status"
echo "# 4. Complete document collection when all documents are uploaded and validated"
echo ""

echo -e "${BLUE}Document Types Supported:${NC}"
echo "- government_id (Driver's License, Passport, State ID)"
echo "- income_verification (Paystubs, Tax Returns, W2)"
echo "- bank_statement (Monthly bank statements)"
echo "- employment_verification (Employment letter, HR verification)"
echo "- proof_of_address (Utility bills, lease agreement)"
echo "- other (Miscellaneous documents)"
echo ""

echo -e "${BLUE}Authentication:${NC}"
echo "Replace 'your-jwt-token-here' with a valid JWT token from your authentication system."
echo ""

echo -e "${BLUE}Language Support:${NC}"
echo "Use X-Language header with 'en' for English or 'vi' for Vietnamese."
echo ""

echo "================================================="
echo "End of Document Management API Examples"
echo "================================================="
