# Pre-qualification Workflow Configuration

# Workflow Engine Configuration
workflow:
  engine: "netflix_conductor"
  conductor:
    base_url: "http://localhost:8082"
    api_version: "v1"
    timeout_seconds: 30
    retry_attempts: 3
    retry_delay_seconds: 5

# Task Worker Configuration
worker:
  poll_interval_seconds: 5
  max_concurrent_tasks: 10
  task_timeout_seconds: 300
  heartbeat_interval_seconds: 30

# Pre-qualification Rules
prequalification:
  # DTI Ratio thresholds
  dti:
    max_ratio: 0.43
    warning_threshold: 0.36
    high_risk_threshold: 0.40
  
  # Income thresholds
  income:
    minimum_annual: 25000
    moderate_threshold: 35000
    high_threshold: 50000
  
  # Loan amount limits
  loan:
    minimum_amount: 5000
    maximum_amount: 50000
    max_income_multiplier: 0.8
  
  # Interest rate configuration
  interest_rates:
    base_rate: 8.0
    dti_adjustment:
      low: -0.5
      medium: 1.5
      high: 3.0
    income_adjustment:
      low: 1.0
      medium: 0.5
      high: -1.0
    employment_adjustment:
      unemployed: 4.0
      part_time: 1.5
      self_employed: 1.0
      full_time: 0.0
  
  # Term recommendations
  terms:
    short: [36, 48]
    medium: [36, 48, 60]
    long: [36, 48, 60, 72]
    income_thresholds:
      low: 35000
      medium: 50000

# Validation Rules
validation:
  required_fields:
    - "userId"
    - "loanAmount"
    - "annualIncome"
    - "employmentStatus"
  
  field_limits:
    loanAmount:
      min: 5000
      max: 50000
    annualIncome:
      min: 25000
    monthlyDebt:
      min: 0
  
  employment_statuses:
    - "full_time"
    - "part_time"
    - "self_employed"
    - "retired"
    - "student"

# Risk Assessment Configuration
risk_assessment:
  risk_levels:
    low: "LOW"
    medium: "MEDIUM"
    high: "HIGH"
  
  risk_factors:
    dti_ratio:
      low: 0.30
      medium: 0.36
      high: 0.43
    income:
      low: 35000
      medium: 50000
    employment:
      high_risk: ["unemployed"]
      medium_risk: ["part_time", "self_employed"]
      low_risk: ["full_time", "retired"]

# Workflow Timeouts
timeouts:
  workflow_execution: 300  # 5 minutes
  task_execution: 60       # 1 minute
  status_polling: 30       # 30 seconds
  result_extraction: 10    # 10 seconds

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  include_workflow_id: true
  include_task_id: true
  include_user_id: true
