# Development Environment Configuration

# Override base configuration for development
server:
  port: "8082"
  cors_enabled: true
  cors_origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:8081"

database:
  url: "postgres://user:password@localhost:5432/decision_engine_dev?sslmode=disable"
  auto_migrate: true

redis:
  host: "localhost"
  port: "6379"
  db: 2

logger:
  level: "debug"
  format: "console"

# Development-specific decision engine settings
decision_engine:
  risk_assessment:
    # More lenient settings for development
    min_credit_score: 500
    max_dti_ratio: 0.60
    min_annual_income: 20000.0
    
  # Lower interest rates for development testing
  interest_rates:
    base_rate: 5.0
    
external_services:
  credit_bureau:
    # Mock service for development
    base_url: "http://localhost:8083/mock"
    timeout: "5s"
    
  notification_service:
    base_url: "http://localhost:8084"

# Enable debug features
debug:
  enable_test_endpoints: true
  log_requests: true
  mock_external_services: true
